export const ALL_PRDOUCT_REQUEST = "ALL_PRDOUCT_REQUEST";
export const ALL_PRDOUCT_SUCCESS = "ALL_PRDOUCT_SUCCESS";
export const ALL_PRDOUCT_FAIL = "ALL_PRDOUCT_FAIL";


export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS"; 