export const ALL_PRDOUCT_REQUEST = "ALL_PRDOUCT_REQUEST";
export const ALL_PRDOUCT_SUCCESS = "ALL_PRDOUCT_SUCCESS";
export const ALL_PRDOUCT_FAIL = "ALL_PRDOUCT_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";